export const firstRow = [
  {
    class: 'key',
    keycode: 'Backquote',
    rus: ['ё', 'Ё', 'Ё', 'ё'],
    eng: ['`', '~', '`', '~'],
  },
  {
    class: 'key',
    keycode: 'Digit1',
    rus: ['1', '!', '1', '!'],
    eng: ['1', '!', '1', '!'],
  },
  {
    class: 'key',
    keycode: 'Digit2',
    rus: ['2', '"', '2', '"'],
    eng: ['2', '@', '2', '@'],
  },
  {
    class: 'key',
    keycode: 'Digit3',
    rus: ['3', '№', '3', '№'],
    eng: ['3', '#', '3', '#'],
  },
  {
    class: 'key',
    keycode: 'Digit4',
    rus: ['4', ';', '4', ';'],
    eng: ['4', '$', '4', '$'],
  },
  {
    class: 'key',
    keycode: 'Digit5',
    rus: ['5', '%', '5', '%'],
    eng: ['5', '%', '5', '%'],
  },
  {
    class: 'key',
    keycode: 'Digit6',
    rus: ['6', ':', '6', ':'],
    eng: ['6', '^', '6', '^'],
  },
  {
    class: 'key',
    keycode: 'Digit7',
    rus: ['7', '?', '7', '?'],
    eng: ['7', '&', '7', '&'],
  },
  {
    class: 'key',
    keycode: 'Digit8',
    rus: ['8', '*', '8', '*'],
    eng: ['8', '*', '8', '*'],
  },
  {
    class: 'key',
    keycode: 'Digit9',
    rus: ['9', '(', '9', '('],
    eng: ['9', '(', '9', '('],
  },
  {
    class: 'key',
    keycode: 'Digit0',
    rus: ['0', ')', '0', ')'],
    eng: ['0', ')', '0', ')'],
  },
  {
    class: 'key',
    keycode: 'Minus',
    rus: ['-', '_', '-', '_'],
    eng: ['-', '_', '-', '_'],
  },
  {
    class: 'key',
    keycode: 'Equal',
    rus: ['=', '+', '=', '+'],
    eng: ['=', '+', '=', '+'],
  },
  {
    class: 'key key__backspace',
    keycode: 'Backspace',
    rus: ['Backspace', 'Backspace', 'Backspace', 'Backspace'],
    eng: ['Backspace', 'Backspace', 'Backspace', 'Backspace'],
  },
];

export const secondRow = [
  {
    class: 'key key__tab',
    keycode: 'Tab',
    rus: ['Tab', 'Tab', 'Tab', 'Tab'],
    eng: ['Tab', 'Tab', 'Tab', 'Tab'],
  },
  {
    class: 'key',
    keycode: 'KeyQ',
    rus: ['й', 'Й', 'Й', 'й'],
    eng: ['q', 'Q', 'Q', 'q'],
  },
  {
    class: 'key',
    keycode: 'KeyW',
    rus: ['ц', 'Ц', 'Ц', 'ц'],
    eng: ['w', 'W', 'W', 'w'],
  },
  {
    class: 'key',
    keycode: 'KeyE',
    rus: ['у', 'У', 'У', 'у'],
    eng: ['e', 'E', 'E', 'e'],
  },
  {
    class: 'key',
    keycode: 'KeyR',
    rus: ['к', 'К', 'К', 'к'],
    eng: ['r', 'R', 'R', 'r'],
  },
  {
    class: 'key',
    keycode: 'KeyT',
    rus: ['е', 'Е', 'Е', 'е'],
    eng: ['t', 'T', 'T', 't'],
  },
  {
    class: 'key',
    keycode: 'KeyY',
    rus: ['н', 'Н', 'Н', 'н'],
    eng: ['y', 'Y', 'Y', 'y'],
  },
  {
    class: 'key',
    keycode: 'KeyU',
    rus: ['г', 'Г', 'Г', 'г'],
    eng: ['u', 'U', 'U', 'u'],
  },
  {
    class: 'key',
    keycode: 'KeyI',
    rus: ['ш', 'Ш', 'Ш', 'ш'],
    eng: ['i', 'I', 'I', 'i'],
  },
  {
    class: 'key',
    keycode: 'KeyO',
    rus: ['щ', 'Щ', 'Щ', 'щ'],
    eng: ['o', 'O', 'O', 'o'],
  },
  {
    class: 'key',
    keycode: 'KeyP',
    rus: ['з', 'З', 'З', 'з'],
    eng: ['p', 'P', 'P', 'p'],
  },
  {
    class: 'key',
    keycode: 'BracketLeft',
    rus: ['х', 'Х', 'Х', 'х'],
    eng: ['[', '{', '[', '{'],
  },
  {
    class: 'key',
    keycode: 'BracketRight',
    rus: ['ъ', 'Ъ', 'Ъ', 'ъ'],
    eng: [']', '}', ']', '}'],
  },
  {
    class: 'key',
    keycode: 'Backslash',
    rus: ['\\', '/', '\\', '/'],
    eng: ['\\', '|', '\\', '|'],
  },
  {
    class: 'key key__del',
    keycode: 'Delete',
    rus: ['Del', 'Del', 'Del', 'Del'],
    eng: ['Del', 'Del', 'Del', 'Del'],
  },
];

export const thirdRow = [
  {
    class: 'key key__caps-lock',
    keycode: 'CapsLock',
    rus: ['CapsLock', 'CapsLock', 'CapsLock', 'CapsLock'],
    eng: ['CapsLock', 'CapsLock', 'CapsLock', 'CapsLock'],
  },
  {
    class: 'key',
    keycode: 'KeyA',
    rus: ['ф', 'Ф', 'Ф', 'ф'],
    eng: ['a', 'A', 'A', 'a'],
  },
  {
    class: 'key',
    keycode: 'KeyS',
    rus: ['ы', 'Ы', 'Ы', 'ы'],
    eng: ['s', 'S', 'S', 's'],
  },
  {
    class: 'key',
    keycode: 'KeyD',
    rus: ['в', 'В', 'В', 'в'],
    eng: ['d', 'D', 'D', 'd'],
  },
  {
    class: 'key',
    keycode: 'KeyF',
    rus: ['а', 'А', 'А', 'а'],
    eng: ['f', 'F', 'F', 'f'],
  },
  {
    class: 'key',
    keycode: 'KeyG',
    rus: ['п', 'П', 'П', 'п'],
    eng: ['g', 'G', 'G', 'g'],
  },
  {
    class: 'key',
    keycode: 'KeyH',
    rus: ['р', 'Р', 'Р', 'р'],
    eng: ['h', 'H', 'H', 'h'],
  },
  {
    class: 'key',
    keycode: 'KeyJ',
    rus: ['о', 'О', 'О', 'о'],
    eng: ['j', 'J', 'J', 'j'],
  },
  {
    class: 'key',
    keycode: 'KeyK',
    rus: ['л', 'Л', 'Л', 'л'],
    eng: ['k', 'K', 'K', 'k'],
  },
  {
    class: 'key',
    keycode: 'KeyL',
    rus: ['д', 'Д', 'Д', 'д'],
    eng: ['l', 'L', 'L', 'l'],
  },
  {
    class: 'key',
    keycode: 'Semicolon',
    rus: ['ж', 'Ж', 'Ж', 'ж'],
    eng: [';', ':', ';', ';'],
  },
  {
    class: 'key',
    keycode: 'Quote',
    rus: ['э', 'Э', 'Э', 'э'],
    eng: ["'", '"', "'", '"'],
  },
  {
    class: 'key key__enter',
    keycode: 'Enter',
    rus: ['Enter', 'Enter', 'Enter', 'Enter'],
    eng: ['Enter', 'Enter', 'Enter', 'Enter'],
  },
];

export const fourthRow = [
  {
    class: 'key key__shift',
    keycode: 'ShiftLeft',
    rus: ['Shift', 'Shift', 'Shift', 'Shift'],
    eng: ['Shift', 'Shift', 'Shift', 'Shift'],
  },
  {
    class: 'key',
    keycode: 'KeyZ',
    rus: ['я', 'Я', 'Я', 'я'],
    eng: ['z', 'Z', 'Z', 'z'],
  },
  {
    class: 'key',
    keycode: 'KeyX',
    rus: ['ч', 'Ч', 'Ч', 'ч'],
    eng: ['x', 'X', 'X', 'x'],
  },
  {
    class: 'key',
    keycode: 'KeyC',
    rus: ['с', 'С', 'С', 'с'],
    eng: ['c', 'C', 'C', 'c'],
  },
  {
    class: 'key',
    keycode: 'KeyV',
    rus: ['м', 'М', 'М', 'м'],
    eng: ['v', 'V', 'V', 'v'],
  },
  {
    class: 'key',
    keycode: 'KeyB',
    rus: ['и', 'И', 'И', 'и'],
    eng: ['b', 'B', 'B', 'b'],
  },
  {
    class: 'key',
    keycode: 'KeyN',
    rus: ['т', 'Т', 'Т', 'т'],
    eng: ['n', 'N', 'N', 'n'],
  },
  {
    class: 'key',
    keycode: 'KeyM',
    rus: ['ь', 'Ь', 'Ь', 'ь'],
    eng: ['m', 'M', 'M', 'm'],
  },
  {
    class: 'key',
    keycode: 'Comma',
    rus: ['б', 'Б', 'Б', 'б'],
    eng: [',', '<', ',', '<'],
  },
  {
    class: 'key',
    keycode: 'Period',
    rus: ['ю', 'Ю', 'Ю', 'ю'],
    eng: ['.', '>', '.', '>'],
  },
  {
    class: 'key',
    keycode: 'Slash',
    rus: ['.', ',', '.', ','],
    eng: ['/', '?', '/', '?'],
  },
  {
    class: 'key key__up',
    keycode: 'ArrowUp',
    rus: ['▲', '▲', '▲', '▲'],
    eng: ['▲', '▲', '▲', '▲'],
  },
  {
    class: 'key key__shift key__shift_right',
    keycode: 'ShiftRight',
    rus: ['Shift', 'Shift', 'Shift', 'Shift'],
    eng: ['Shift', 'Shift', 'Shift', 'Shift'],
  },
];

export const fifthRow = [
  {
    class: 'key key__ctrl',
    keycode: 'ControlLeft',
    rus: ['Ctrl', 'Ctrl', 'Ctrl', 'Ctrl'],
    eng: ['Ctrl', 'Ctrl', 'Ctrl', 'Ctrl'],
  },
  {
    class: 'key key__win',
    keycode: 'MetaLeft',
    rus: ['Win', 'Win', 'Win', 'Win'],
    eng: ['Win', 'Win', 'Win', 'Win'],
  },
  {
    class: 'key key__alt',
    keycode: 'AltLeft',
    rus: ['Alt', 'Alt', 'Alt', 'Alt'],
    eng: ['Alt', 'Alt', 'Alt', 'Alt'],
  },
  {
    class: 'key key__space',
    keycode: 'Space',
    rus: ['', '', '', ''],
    eng: ['', '', '', ''],
  },
  {
    class: 'key key__alt key__alt_right',
    keycode: 'AltRight',
    rus: ['Alt', 'Alt', 'Alt', 'Alt'],
    eng: ['Alt', 'Alt', 'Alt', 'Alt'],
  },
  {
    class: 'key key__left',
    keycode: 'ArrowLeft',
    rus: ['◄', '◄', '◄', '◄'],
    eng: ['◄', '◄', '◄', '◄'],
  },
  {
    class: 'key key__down',
    keycode: 'ArrowDown',
    rus: ['▼', '▼', '▼', '▼'],
    eng: ['▼', '▼', '▼', '▼'],
  },
  {
    class: 'key key__right',
    keycode: 'ArrowRight',
    rus: ['►', '►', '►', '►'],
    eng: ['►', '►', '►', '►'],
  },
  {
    class: 'key key__ctrl key__ctrl_right',
    keycode: 'ControlRight',
    rus: ['Ctrl', 'Ctrl', 'Ctrl', 'Ctrl'],
    eng: ['Ctrl', 'Ctrl', 'Ctrl', 'Ctrl'],
  },
];